### PR TITLE
First Major Site Revision

### PR DESCRIPTION
**Pull request by nevetsosu**
I'm actually just not gonna squash merge, that would mean losing commit entries.
Since this is a project where we need to track individual commits, I'll just merge everything and I guess we'll just have nearly 500 to 1000 commits by the end of the project.

### CODE REVIEW

**Review by EliteJono — APPROVED** [review]
looks good to me

**Review by MariAuxHer — APPROVED** [review]
Good! :)

**Review by chesedcaseycollins — APPROVED** [review]
What I've made still works

**Review by amals610 — APPROVED** [review]
all good

**Pull request merged**
